# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Update Content

on:
  schedule: 
    - cron: 0 0 * * MON

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      USER_SECRET: ${{ secrets.SECRET }}
      USER_NAME: ${{ secrets.USER_EMAIL}}
      USER_EMAIL: ${{ secrets.USER_NAME }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: run crawler
      run: |
        python crawler.py
    - name: update repo
      run: |
        git config user.name --local $USER_NAME
        git config user.email --local $USER_EMAIL
        git add content.txt
        git commit -m "$(date +"%Y-%m-%d") update content.txt"
        git push

        
